### ISSUE TITLE
Walkthrough on setting up a station and depot?

### ISSUE THREAD

**Issue by DBosley** [Opinionated-Blueprints/10-Books-Full-of-Rails#16]
This blueprint book is fabulous and I believe it's going to save me a ton of time and effort, but I'm curious about how you set up your stations. Can you provide screenshots of how to set up an efficient stacked station using the stackers? I feel like I'm spending a long time on this when it's probably much simpler than I'm understanding.

A depot example would also be extremely helpful. I assume you set up refueling at your depots as well, but the layout is what's being difficult for me to wrap my head around.

I understand how to set up the platforms, providers, and requestors once a station laid out, but setting up the track itself is what's confusing me.

**Comment by Bocian-1** [comment]
Here's two examples of stations with stackers. Whether you use one of these 'styles' or something completely different is up to you or your needs. For now, all I provide in the book is very modular so you have to assemble it yourself. You won't be able to make those purely using the blueprints, you do need to lay down some rail yourself to connect some parts. These two could be further optimised with better signalling and the one on the left could be made shorter as well by shifting the signalling on the stackers rightward to the turn in the rail and cutting off the excess on the left. Note that the right station has chain signals after the stackers instead of regular. Regular signals are fine when there's only 1 station after the stackers. If there are more you should replace them with chain so that the trains don't block other stations.
![image](https://github.com/user-attachments/assets/aabb44e3-a9e1-4cd7-92e1-b3e45f86c8e1)

You don't need refuelling to be at depots, there's no difference with the current system (it's a bit overengineered to be honest)

**Comment by Bocian-1** [comment]
Regardless, the best stackers are purpose-built yourself, I'm not so sure about the current huge mass of stackers when they don't even eliminate the need for manual adjustments anyway. I'll have to revisit the entire concept

**Comment by Bocian-1** [comment]
> @Bocian-1 By curiosity, what mods do you use to have a convenient maps like that to work on blueprints as well as possibly some helpers mods? What is your modlist in this screenshot?

Editor Extensions and Creative Mod are the main ones
Aside from that:
- Belt Visualiser
- Blueprint Extensions
- Calculator UI
- Cursor Enhancements
- Entity Symmetry
- Factory Planner
- Inserter Visualiser Lite
- RailTester
- Shortcuts for 2.0
- Show Max Underground Distance
- Solar Calculator
- Stats GUI (inconsequential for editor, it's the playtime/evolution etc text)
- Text Plates
And dependencies for some of the above

**Comment by Xiarno** [comment]
> > @Bocian-1 By curiosity, what mods do you use to have a convenient maps like that to work on blueprints as well as possibly some helpers mods? What is your modlist in this screenshot?
> 
> Editor Extensions and Creative Mod are the main ones Aside from that:
> 
> * Belt Visualiser
> * Blueprint Extensions
> * Calculator UI
> * Cursor Enhancements
> * Entity Symmetry
> * Factory Planner
> * Inserter Visualiser Lite
> * RailTester
> * Shortcuts for 2.0
> * Show Max Underground Distance
> * Solar Calculator
> * Stats GUI (inconsequential for editor, it's the playtime/evolution etc text)
> * Text Plates
>   And dependencies for some of the above

Thank you very much!
