### ISSUE TITLE
Big Electric Pole on Rails

### ISSUE THREAD

**Issue by divine-ray** [Opinionated-Blueprints/10-Books-Full-of-Rails#18]
Hello,
what is the reasoning behind the rather short 12 tiles between each pole, being half of their ideal capacity of 32?

And while I'm here, i want to ask for the reasoning behind the rather arbitrary 42x42 tile grid (as opposed to a standard 16x16 chunk aligned grid).

**Comment by Bocian-1** [comment]
What do I do so people see it...
![image](https://github.com/user-attachments/assets/48970593-6e98-4435-8a9b-402157a433cd)

42x42 isn't "arbitrary". It's the exact length of a 6-car train. Chunk aligned has been completely pointless and useless since grid snapping has been added. There has been literally 0 reason to build anything chunk-aligned for like 3+ years now.

**Comment by rpdelaney** [comment]
Please open a discussions thread for questions like this.
