### ISSUE TITLE
Train park at provider station instead of depot

### ISSUE THREAD

**Issue by Tuaz** [Opinionated-Blueprints/10-Books-Full-of-Rails#38]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

2.15.0

### Bug Description

Train park at provider station even when no request station for that item is built 

### How to reproduce the problem

I built requester/provider station and depot using blueprints. 
![factorio_P6V5V37pfj](https://github.com/user-attachments/assets/2f4cf637-8bf5-44c0-adc2-5aebf9d64b82)

### What did you expect?

I execpt the train to go to depot when all requests are fulfilled and not going to provider station

### What happened instead?

The train parks at provider station and wait for requests

**Comment by brandon-gradient** [comment]
I think the problem can be that if this functions like you expect that it's possible the depot will fill up with trains full of stone or something else that there is a lot of "provided" but not requested. This could then starve all other providers because there are no empty trains as all trains at the depot are full of something that isn't needed.

If using a resource-dedicated train the behavior described is fine because the train picking up iron plates, as in your example, is only used for this purpose and will thus not cause other providers or requesters to be starved as it would never service them to begin with.

**Comment by Bocian-1** [comment]
> I think the problem can be that if this functions like you expect that it's possible the depot will fill up with trains full of stone or something else that there is a lot of "provided" but not requested. This could then starve all other providers because there are no empty trains as all trains at the depot are full of something that isn't needed.
> 
> If using a resource-dedicated train the behavior described is fine because the train picking up iron plates, as in your example, is only used for this purpose and will thus not cause other providers or requesters to be starved as it would never service them to begin with.

Correct. This is intended behaviour. Just make more trains.

**Comment by Bocian-1** [comment]
> I was thinking the train at the depot would be empty and check if request station is available before going to the a provider station to fill up
That would be more complicated to set up and less efficient as the train would have to be loaded first, where currently that will already have happened, so response times would be greater. Since current system makes trains wait at providers, the provider stations effectively function as depots, so you don't really need many of those. In fact you only need exactly as many depots as yo have trains minus number of provider stations and their stacker slots. If they waited at depots, you'd need as many depots as trains period. The only "downside" to the current system as opposed to waiting at depots before going to providers is you need more trains, but if they wait at the providers, they don't contribute to traffic anyway and their paths are more direct, not visiting depots nearly as often so they stay on the track for a shorter time as well. Cost of trains is a joke and not even worth mentioning.
