### ISSUE TITLE
How does the train limit system work?

### ISSUE THREAD

**Issue by Fireball5939** [Opinionated-Blueprints/10-Books-Full-of-Rails#4]
In specific I'm looking at how this one works, though an explanation on how the requester train limit works would also be helpful.
![image](https://github.com/Bocian-1/10-Books-Full-of-Rails/assets/111195856/15563f42-13e0-4bdc-be52-f21571a5eacf)
From what I understand, it's taking the inputs from the chests, see below image, dividing each item's value by 0, then outputting to signal "D" and then the constant combinator is just outputting 0 on signal "M". 
![image](https://github.com/Bocian-1/10-Books-Full-of-Rails/assets/111195856/b0506a40-8a97-4333-876d-b4733a5b143c)
After that it then basically outputs the value of whatever signal is smaller to the train station as the train limit. From my understanding that would, in most scenarios, have signal "M" be equal to the train limit unless you had some insane number for it, but at that point wouldn't it just be easier to set the limit in the train station's GUI?

**Comment by Bocian-1** [comment]
It sets the limit dynamically according to the amount of resources at the station.
`D` (delivery) tracks how many trains it can service without stalling due to lack of resources to load or space to unload
`M` (max) is the cap for the train limit
The lower value is always chosen

For providers, the train limit then would correspond to the number of trains they can fully load but no more than `M`
And for requesters it would be the number of deliveries they can fully unload but no more than `M`

This way you don't have trains going to provider stations that don't have enough resources to load them or requester stations that don't have enough space for unloading.

They don't work out of the bag though, you need to set some combinator settings yourself according to the tooltips:
![image](https://github.com/Bocian-1/10-Books-Full-of-Rails/assets/70019596/c16a82ba-5420-4827-acdd-1c552456d190)
![image](https://github.com/Bocian-1/10-Books-Full-of-Rails/assets/70019596/8f30d523-f872-4bb0-b5d8-a74e1a73bb54)
Also remember to attach wires on power poles if you place the buffer on the opposite side of the track to the station (I forget this all the time)

**Comment by rpdelaney** [comment]
Btw, here's what I came up with for a train limiter before I found Bocian's. I haven't done a comparison so I can't say it's better or anything like that, but maybe it can be useful to someone.

https://factoriobin.com/post/ZTkzOT9M

**Comment by rpdelaney** [comment]
I've opened up [discussions](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions) for questions and discussion. Please feel free to ask for help over there!
