### ISSUE TITLE
Seemingly incorrect params being used when creating stations

### ISSUE THREAD

**Issue by goralight** [Opinionated-Blueprints/10-Books-Full-of-Rails#54]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v2.18

### Bug Description

Incorrect params being used when creating stations

### How to reproduce the problem

1. Create a requester station
2. Enter in some params (I gave it group `1`, and item `iron ore`, max one train, 2 carriages. Iee image below)
3. Power up
4. Notice some signals seem off, for example, train limit is set to `-2` on the station.

![image](https://github.com/user-attachments/assets/4a0f2f61-f079-42d2-98e8-6a3c69bb6540)

It isn't letting trains arrive at the station either.
Older stations (ones already placed) are working as intended, it's just new stations.

This was working before the Factorio Update (`2.0.20`) today, but that might be a coincidence.

If you need images of specific logic items then please ask and I can provide.

### What did you expect?

Correctly sets up the signals so that trains in the correct group get sent correctly.

### What happened instead?

It seems that the signals are incorrect, and thus aren't sending trains correctly to said stations

**Comment by Bocian-1** [comment]
Did you leave Buffer `Chests per Wagon` at -2?

**Comment by goralight** [comment]
Besides changing the group, item, max train limit and cargo wagons - everything else is default.
Does this mean I need to put the insertors down first, and then the train stop? if so I'm sorry 😅

**Comment by Bocian-1** [comment]
There is a problem with setting defaults in parameterised blueprints as every instance of a given signal or value is merged into a single parameter, so if you have multiple values that are separate but you would like to have identical defaults - that is not possible. In this case, I'd like the defaults to be 4 for cargo wagons and 4 for buffer chests per wagon, but I can't do that for the above reason. That's why I set the chests to -2 to hopefully make it clearer it needs to be modified.

You may be interested in the wiki page:
https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki/Provider-and-Requester-stations
